version: "3.8"

services:
  mongodb:
    image: mongo:7.0
    container_name: flowbitai-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    command: mongod --replSet rs0 --bind_ip_all
    networks:
      - flowbitai-network

  # Optional: MongoDB Express for database management UI
  mongo-express:
    image: mongo-express:1.0.2
    container_name: flowbitai-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb
    networks:
      - flowbitai-network

volumes:
  mongodb_data:

networks:
  flowbitai-network:
    driver: bridge
