version: "3.8"

services:
  mongodb:
    image: mongo:7
    container_name: flowbitai-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    command: mongod --replSet rs0 --bind_ip_all
    networks:
      - flowbitai-network

  mongo-express:
    image: mongo-express:latest
    container_name: flowbitai-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/flowbitai?directConnection=true
      ME_CONFIG_BASICAUTH_USERNAME: webadmin
      ME_CONFIG_BASICAUTH_PASSWORD: webpassword123
      ME_CONFIG_BASICAUTH: true
    depends_on:
      - mongodb
    networks:
      - flowbitai-network

  api:
    build: .
    container_name: flowbitai-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "mongodb://mongodb:27017/flowbitai?directConnection=true"
      JWT_SECRET: "myjwtsecret"
      PORT: 3000
      NODE_ENV: production
    volumes:
      - .:/app
      - /app/node_modules
    command: npx tsx api/index.ts
    depends_on:
      - mongodb
    networks:
      - flowbitai-network

  n8n:
    image: n8nio/n8n
    container_name: flowbitai-n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      N8N_USER_MANAGEMENT_DISABLED: true
      N8N_DIAGNOSTICS_ENABLED: false
      N8N_VERSION_NOTIFICATIONS_ENABLED: false
      N8N_TEMPLATES_ENABLED: false
      WEBHOOK_URL: http://localhost:5678
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - flowbitai-network

volumes:
  mongodb_data:
  n8n_data:

networks:
  flowbitai-network:
    driver: bridge
